### ISSUE TITLE
Script not approved on Greasy Fork

### ISSUE THREAD

**Issue by marlarius** [CoeJoder/waitForKeyElements.js#2]
Hi,

I cannot publish a script using your much enhanced version of WaitForKeyElements. Any chance you can get it approved, or do you know of a version that is already approved?

Thanks,
Martin

**Comment by CoeJoder** [comment]
Hi @marlarius
I see it is already published [there](https://greasyfork.org/en/scripts/502635-waitforkeyelements-coejoder-fork/code).  The mods at GreasyFork can be a little overzealous and boneheaded in enforcing software licenses, as you can see from the [parent project's gist thread](https://gist.github.com/BrockA/2625891).  Best of luck.
